### ISSUE TITLE
The Module breaks Angular 5

### ISSUE THREAD

**Issue by edmondko** [lokenxo/ng2-fittext#16]
After updating Angular 5 and Angular CLI 1.5 I get the error when I run `ng serve`:
```
ERROR in ./node_modules/ng2-fittext/ng2fittext.ts
Module build failed: Error: C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\ng2-fittext\ng2fittext.ts is not part of
 the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\@ngtools\webpack\src\a
ngular_compiler_plugin.js:629:23)
    at plugin.done.then (C:\xampp\htdocs\webpages\ios\ng-gopremium\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/app.module.ts 21:0-58
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by edmondko** [comment]
on ng build --prod I get this error:
```
ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing
the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbo
l NgModule in C:/xampp/htdocs/webpages/ios/ng-gopremium/node_modules/ng2-fittext/node_modules/@angular/core/core.d.ts, reso
lving symbol Ng2FittextModule in C:/xampp/htdocs/webpages/ios/ng-gopremium/node_modules/ng2-fittext/src/ng2fittext.module.t
s, resolving symbol Ng2FittextModule in C:/xampp/htdocs/webpages/ios/ng-gopremium/node_modules/ng2-fittext/src/ng2fittext.m
odule.ts
```

**Comment by martinduris** [comment]
hi,
in 2 weeks i can try to look at it ;-)

**Comment by thisloke** [comment]
I'll migrate to angular5 soon, so i'll be able to investigate. 

Thanks for the notification 👍

**Comment by edmondko** [comment]
@lokenxo I've downloaded only  the directive in my `src/app` folder and it's totally usable and working, fixing the module would be enough to support the library. Great work by the way, thanks for the quick response.

**Comment by thisloke** [comment]
Perfect! It's a temporary solution, but early i'll fix the module.

**Comment by thisloke** [comment]
Fixed.
