### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by kupecraig** [lokenxo/ng2-fittext#34]
ERROR in ./node_modules/ng2-fittext/fesm5/ng2-fittext.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16740:24)
    at checkNodeForDecorators (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\work\sc\sc-petquote\sc-petquote-angular\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16599:21)

**Comment by lorenzo-iovino** [comment]
Could you post also your package.json content?

**Comment by kupecraig** [comment]
{
  "name": "app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --watch -o",
    "build": "ng build --extractCss --watch --prod=true --outputHashing=none",
    "build-prod": "ng build --prod=true  --outputHashing=none",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.13",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.13",
    "@angular/compiler": "^8.2.13",
    "@angular/core": "^8.2.13",
    "@angular/forms": "^8.2.13",
    "@angular/material": "^8.2.3",
    "@angular/material-moment-adapter": "^8.2.3",
    "@angular/platform-browser": "^8.2.13",
    "@angular/platform-browser-dynamic": "^8.2.13",
    "@angular/router": "^8.2.13",
    "@types/greensock": "^1.15.32",
    "@types/gsap": "^1.20.2",
    "@types/jquery": "^3.3.32",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.6.10",
    "gsap": "^2.1.3",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "mobx": "^5.14.2",
    "mobx-angular": "^3.0.2",
    "moment": "^2.24.0",
    "rxjs": "~6.4.0",
    "rxjs-compat": "^6.5.3",
    "save": "^2.4.0",
    "tslib": "^1.9.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.6",
    "@angular/cli": "^8.3.17",
    "@angular/compiler-cli": "^8.2.13",
    "@angular/language-service": "^8.2.13",
    "@types/jasmine": "^3.3.16",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "~8.9.4",
    "axe-core": "^3.4.1",
    "codelyzer": "^5.2.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.6",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}

**Comment by thisloke** [comment]
I can't find in you package.json the ng2-fittrext module, are you sure you have installed all correctly?

I suggest you to do a clean and a new installation of all your module,  i don't think is a problem related the library.

**Comment by arazinger** [comment]
I have the same problem with version "1.2.12".

When building a production version I get:

ERROR in ./node_modules/ng2-fittext/fesm5/ng2-fittext.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/ales/Developer/angular/projects/app.web/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16599:21)
npm ERR! code ELIFECYCLE


I'm using Angular 8:

Angular CLI: 8.0.6
Node: 10.16.0
OS: darwin x64
Angular: 8.2.8
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cdk                      8.2.1
@angular/cli                      8.0.6
@angular/compiler-cli             8.0.3
@angular/flex-layout              8.0.0-beta.27
@angular/language-service         8.0.3
@angular/material                 8.2.1
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.5.3
typescript                        3.4.5
webpack                           4.30.0

**Comment by KirstenStake** [comment]
@arazinger did you find a solution for this? getting the same error and have opened a new issue for it.

**Comment by arazinger** [comment]
> @arazinger did you find a solution for this? getting the same error and have opened a new issue for it.

No, didn't find it, but as a workaround I'm using this version of a package which works: "ng2-fittext": "1.2.8"

**Comment by KirstenStake** [comment]
@arazinger downgrading the package doesn't show the error anymore. will have to do this for now as well. thanks for your help!
